from __future__ import annotations

import os

os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"

import argparse
from pathlib import Path
import sys

import matplotlib.pyplot as plt
import numpy as np
from scipy.optimize import minimize
import torch

if __package__ is None or __package__ == "":
    sys.path.append(str(Path(__file__).resolve().parents[1]))
    from icnn_lyapunov.controller import compute_control_action_theta
    from icnn_lyapunov.models import GammaICNN
else:
    from .controller import compute_control_action_theta
    from .models import GammaICNN

try:
    from motor import A_list, B_list, motor_step
except ModuleNotFoundError:
    sys.path.append(str(Path(__file__).resolve().parents[1]))
    from motor import A_list, B_list, motor_step


def _project_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _infer_hidden_sizes_from_state_dict(state_dict: dict[str, torch.Tensor]) -> tuple[int, ...]:
    hidden = []
    layer_id = 0
    while f"x_layers.{layer_id}.weight" in state_dict:
        hidden.append(int(state_dict[f"x_layers.{layer_id}.weight"].shape[0]))
        layer_id += 1
    if not hidden:
        raise ValueError(
            "Cannot infer GammaICNN hidden sizes from checkpoint. "
            "Use a checkpoint saved by train_gamma_icnn.py."
        )
    return tuple(hidden)


def load_gamma_icnn(
    checkpoint_path: str | Path,
    *,
    device: str | torch.device = "cpu",
) -> GammaICNN:
    """Load a GammaICNN checkpoint generated by train_gamma_icnn.py."""
    path = Path(checkpoint_path)
    if not path.is_absolute():
        path = _project_root() / path
    if not path.exists():
        raise FileNotFoundError(f"Checkpoint not found: {path}")

    checkpoint = torch.load(path, map_location=device)
    if isinstance(checkpoint, dict) and "model_state_dict" in checkpoint:
        state_dict = checkpoint["model_state_dict"]
        input_dim = int(checkpoint["input_dim"])
        hidden_sizes = tuple(checkpoint["hidden_sizes"])
        activation = checkpoint.get("activation", "softplus")
        enforce_positive_output = bool(checkpoint.get("enforce_positive_output", True))
        feature_mode = checkpoint.get("feature_mode", "state_u" if input_dim == 3 else "state")
    else:
        state_dict = checkpoint
        input_dim = int(state_dict["input_mean"].numel())
        hidden_sizes = _infer_hidden_sizes_from_state_dict(state_dict)
        activation = "softplus"
        enforce_positive_output = True
        feature_mode = "state_u" if input_dim == 3 else "state"

    model = GammaICNN(
        input_dim=input_dim,
        hidden_sizes=hidden_sizes,
        activation=activation,
        enforce_positive_output=enforce_positive_output,
    ).to(device)
    model.load_state_dict(state_dict)
    model.feature_mode = feature_mode
    model.project_nonnegative_weights()
    model.eval()
    return model


def _as_state_vector(x: np.ndarray | list[float] | tuple[float, ...]) -> np.ndarray:
    x_vec = np.asarray(x, dtype=float).reshape(-1)
    if x_vec.size != 2:
        raise ValueError(f"This motor example expects a 2D state, got shape {x_vec.shape}.")
    return x_vec


def _step_motor_flat(x: np.ndarray, u: float, *, vertex_id: int) -> np.ndarray:
    """Call the existing motor_step safely and return a flat 2D state."""
    x_col = np.asarray(x, dtype=float).reshape(2, 1)
    x_next = motor_step(x_col, float(u), vertex_id=vertex_id)
    return np.asarray(x_next, dtype=float).reshape(-1)


def _step_linear_flat(x: np.ndarray, u: float, *, vertex_id: int) -> np.ndarray:
    """Fast NumPy prediction model matching motor_step."""
    return (A_list[vertex_id] @ x.reshape(2, 1) + B_list[vertex_id] * float(u)).reshape(-1)


def _build_icnn_input(
    x: np.ndarray,
    u: float,
    model: GammaICNN,
    *,
    vertex_id: int,
) -> np.ndarray:
    """Build the feature vector expected by the trained ICNN.

    If the model feature mode is state_u, the feature is [x1, x2, u]. If the
    model feature mode is state, the model is assumed to approximate gamma(x),
    so the optimized feature is x_next = f(x,u).
    """
    input_dim = int(model.input_dim)
    feature_mode = getattr(model, "feature_mode", "state_u" if input_dim == 3 else "state")
    if input_dim == 3 and feature_mode == "state_u":
        return np.array([x[0], x[1], float(u)], dtype=np.float32)
    if input_dim == 2 and feature_mode == "state":
        return _step_motor_flat(x, float(u), vertex_id=vertex_id).astype(np.float32)
    if feature_mode == "state_ubound":
        raise ValueError(
            "This checkpoint was trained with [x, u_bound], not [x, u]. "
            "Retrain with --feature-mode state_u for closed-loop optimization over u."
        )
    raise ValueError(
        f"Unsupported GammaICNN input_dim={input_dim}. "
        "Expected 2 for gamma(x_next) or 3 for gamma(x,u)."
    )


def predict_gamma(
    x: np.ndarray,
    u: float,
    model: GammaICNN,
    *,
    vertex_id: int,
    device: torch.device,
) -> float:
    features = _build_icnn_input(x, u, model, vertex_id=vertex_id)
    with torch.no_grad():
        tensor = torch.as_tensor(features, dtype=torch.float32, device=device).unsqueeze(0)
        return float(model(tensor).squeeze().cpu().item())


def predict_gamma_from_features(
    features: np.ndarray,
    model: GammaICNN,
    *,
    device: torch.device,
) -> float:
    with torch.no_grad():
        tensor = torch.as_tensor(features, dtype=torch.float32, device=device).unsqueeze(0)
        return float(model(tensor).squeeze().cpu().item())


def compute_control_scipy(
    x: np.ndarray,
    model: GammaICNN,
    *,
    u_max: float,
    vertex_id: int,
    device: torch.device,
    F: np.ndarray | None = None,
    horizon: int = 1,
    state_weight: float = 0.0,
    control_weight: float = 1e-4,
    optimizer_method: str = "Powell",
) -> tuple[float, float]:
    """Minimize the ICNN gamma prediction with scipy.optimize.minimize.

    For feature_mode=state and horizon > 1, SciPy optimizes a finite sequence
    [u_k, ..., u_{k+H-1}] through the predicted dynamics and applies only u_k.
    This is useful when the input affects the value function with a delay.
    """
    x = _as_state_vector(x)
    horizon = max(int(horizon), 1)
    if F is not None:
        u0 = float(np.asarray(F, dtype=float).reshape(1, -1) @ x.reshape(-1, 1))
    else:
        u0 = 0.0
    u0 = float(np.clip(u0, -u_max, u_max))
    feature_mode = getattr(model, "feature_mode", "state_u" if model.input_dim == 3 else "state")

    def objective(u_array: np.ndarray) -> float:
        if feature_mode == "state" and horizon > 1:
            x_pred = x.copy()
            running_cost = 0.0
            for u_step in u_array:
                x_pred = _step_linear_flat(x_pred, float(u_step), vertex_id=vertex_id)
                running_cost += state_weight * float(x_pred @ x_pred)
                running_cost += control_weight * float(u_step * u_step)
            terminal_gamma = predict_gamma_from_features(
                x_pred,
                model,
                device=device,
            )
            return terminal_gamma + running_cost
        return predict_gamma(
            x,
            float(u_array[0]),
            model,
            vertex_id=vertex_id,
            device=device,
        ) + control_weight * float(u_array[0] * u_array[0])

    x0 = np.full(horizon if feature_mode == "state" else 1, u0, dtype=float)
    result = minimize(
        objective,
        x0=x0,
        method=optimizer_method,
        bounds=[(-float(u_max), float(u_max))] * len(x0),
        options={"maxiter": 120, "ftol": 1e-9},
    )
    if not result.success:
        print(f"Warning: scipy minimize did not fully converge: {result.message}")

    u_opt = float(np.clip(result.x[0], -u_max, u_max))
    gamma_opt = objective(result.x)
    return u_opt, gamma_opt


def simulate_closed_loop(
    model: GammaICNN,
    x0: np.ndarray | list[float] | tuple[float, ...],
    *,
    nsim: int,
    u_max: float,
    vertex_id: int,
    device: torch.device,
    F: np.ndarray | None = None,
    horizon: int = 1,
    state_weight: float = 0.0,
    control_weight: float = 1e-4,
    optimizer_method: str = "Powell",
    control_mode: str = "theta",
    beta: float = 1e-4,
    theta_steps: int = 300,
    theta_lr: float = 5e-2,
) -> dict[str, np.ndarray]:
    x = _as_state_vector(x0)
    x_hist = np.zeros((nsim + 1, 2), dtype=float)
    u_hist = np.zeros(nsim, dtype=float)
    gamma_hist = np.zeros(nsim, dtype=float)
    gamma_current_hist = np.zeros(nsim, dtype=float)
    stable_hist = np.zeros(nsim, dtype=bool)
    f_hist = np.zeros((nsim, 1, 2), dtype=float)
    x_hist[0] = x
    theta_init = None

    for k in range(nsim):
        if control_mode == "theta":
            theta_result = compute_control_action_theta(
                x,
                model,
                A=A_list[vertex_id],
                B=B_list[vertex_id],
                u_max=u_max,
                beta=beta,
                lr=theta_lr,
                n_steps=theta_steps,
                state_weight=state_weight,
                control_weight=control_weight,
                theta_init=theta_init,
            )
            u = float(theta_result.u[0])
            gamma_current_hist[k] = theta_result.gamma_current
            gamma_value = theta_result.gamma_next
            stable_hist[k] = theta_result.stable
            f_hist[k] = theta_result.F
            theta_init = theta_result.theta
        elif control_mode == "u":
            u, gamma_value = compute_control_scipy(
                x,
                model,
                u_max=u_max,
                vertex_id=vertex_id,
                device=device,
                F=F,
                horizon=horizon,
                state_weight=state_weight,
                control_weight=control_weight,
                optimizer_method=optimizer_method,
            )
            gamma_current_hist[k] = np.nan
            stable_hist[k] = False
        else:
            raise ValueError("control_mode must be 'theta' or 'u'.")

        x = _step_motor_flat(x, u, vertex_id=vertex_id)
        x_hist[k + 1] = x
        u_hist[k] = u
        gamma_hist[k] = gamma_value

    return {
        "x": x_hist,
        "u": u_hist,
        "gamma": gamma_hist,
        "gamma_current": gamma_current_hist,
        "stable": stable_hist,
        "F": f_hist,
    }


def plot_results(
    results: list[dict[str, np.ndarray]],
    labels: list[str],
    *,
    title: str,
    save_fig: str | Path | None = None,
    show: bool = True,
) -> None:
    fig, axs = plt.subplots(3, 1, figsize=(9, 8), sharex=True)

    for result, label in zip(results, labels):
        t_x = np.arange(result["x"].shape[0])
        t_u = np.arange(result["u"].shape[0])
        axs[0].plot(t_x, result["x"][:, 0], marker="o", label=label)
        axs[1].plot(t_x, result["x"][:, 1], marker="o", label=label)
        axs[2].step(t_u, result["u"], where="post", label=label)

    axs[0].set_ylabel("$x_1$")
    axs[1].set_ylabel("$x_2$")
    axs[2].set_ylabel("$u$")
    axs[2].set_xlabel("k")
    axs[0].set_title(title)
    for ax in axs:
        ax.grid(True)
        ax.legend()
    plt.tight_layout()
    if save_fig is not None:
        save_path = Path(save_fig)
        if not save_path.is_absolute():
            save_path = _project_root() / save_path
        save_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(save_path, dpi=200)
        print(f"Saved closed-loop figure to {save_path}")
    if show:
        plt.show()
    else:
        plt.close(fig)


def parse_initial_conditions(raw_values: list[float]) -> list[np.ndarray]:
    if len(raw_values) % 2 != 0:
        raise ValueError("--x0 expects pairs: x1 x2 [x1 x2 ...].")
    return [
        np.array(raw_values[i : i + 2], dtype=float)
        for i in range(0, len(raw_values), 2)
    ]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Closed-loop simulation with a trained GammaICNN controller.")
    parser.add_argument("--checkpoint", default="icnn_lyapunov/gamma_icnn.pth")
    parser.add_argument("--nsim", type=int, default=100)
    parser.add_argument("--u-max", type=float, default=2.0)
    parser.add_argument("--vertex-id", type=int, default=1)
    parser.add_argument("--device", default="cpu")
    parser.add_argument("--horizon", type=int, default=8, help="Prediction horizon for gamma(x) checkpoints.")
    parser.add_argument("--state-weight", type=float, default=1.0, help="Optional running state penalty.")
    parser.add_argument("--control-weight", type=float, default=1e-4, help="Small regularization on control effort.")
    parser.add_argument("--optimizer-method", default="Powell", help="SciPy minimize method, e.g. Powell or L-BFGS-B.")
    parser.add_argument("--control-mode", choices=["theta", "u"], default="theta")
    parser.add_argument("--beta", type=float, default=1e-5, help="Small Lyapunov margin B=beta*||x||^2.")
    parser.add_argument("--theta-steps", type=int, default=350)
    parser.add_argument("--theta-lr", type=float, default=5e-2)
    parser.add_argument(
        "--x0",
        type=float,
        nargs="+",
        default=[0.8, 0.4, -0.8, 0.3, 1.2, -0.4],
        help="Initial states as pairs: x1 x2 [x1 x2 ...].",
    )
    parser.add_argument(
        "--F",
        type=float,
        nargs=2,
        default=None,
        help="Optional linear warm-start gain u0 = F x, e.g. --F -1.0 -0.2.",
    )
    parser.add_argument("--save-fig", default="", help="Optional path for saving the closed-loop figure.")
    parser.add_argument("--no-show", action="store_true", help="Do not open the matplotlib window.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    device = torch.device(args.device)
    model = load_gamma_icnn(args.checkpoint, device=device)
    initial_conditions = parse_initial_conditions(args.x0)
    F = np.array(args.F, dtype=float).reshape(1, 2) if args.F is not None else None

    results = []
    labels = []
    for idx, x0 in enumerate(initial_conditions, start=1):
        result = simulate_closed_loop(
            model,
            x0,
            nsim=args.nsim,
            u_max=args.u_max,
            vertex_id=args.vertex_id,
            device=device,
            F=F,
            horizon=args.horizon,
            state_weight=args.state_weight,
            control_weight=args.control_weight,
            optimizer_method=args.optimizer_method,
            control_mode=args.control_mode,
            beta=args.beta,
            theta_steps=args.theta_steps,
            theta_lr=args.theta_lr,
        )
        results.append(result)
        labels.append(f"x0 #{idx}: [{x0[0]:.2f}, {x0[1]:.2f}]")
        stable_count = int(np.count_nonzero(result["stable"]))
        print(
            f"{labels[-1]} | final x = [{result['x'][-1, 0]:.4f}, {result['x'][-1, 1]:.4f}] | "
            f"max |u| = {np.max(np.abs(result['u'])):.4f} | last gamma = {result['gamma'][-1]:.4e} | "
            f"Lyapunov ok {stable_count}/{len(result['stable'])}"
        )

    plot_results(
        results,
        labels,
        title="Closed-loop GammaICNN control",
        save_fig=args.save_fig or None,
        show=not args.no_show,
    )


if __name__ == "__main__":
    main()
